name: Mirror to Codeberg
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          # Fetch the entire history
          submodules: recursive   # Initialize submodules

      - name: Initialize and update submodules explicitly
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.THT_CODEBERG }}
        run: |
          # Add Codeberg remote for the main repository
          git remote add codeberg https://$CODEBERG_TOKEN@codeberg.org/Thatoneham/JustStudy-CE.git
          
          # Push submodules
          git submodule foreach --recursive '
            # Ensure submodule is on a branch (e.g., main)
            git checkout main || git checkout -b main
            git remote add codeberg https://$CODEBERG_TOKEN@codeberg.org/Thatoneham/SubmoduleRepo.git || true
            git push --force codeberg main
          '

          # Push the main repository with submodules
          git push --recurse-submodules=on-demand codeberg main --force
